[package]
name = "crypt3_nif"
version = "0.1.0"
authors = ["Antoine Gagné <gagnantoine@gmail.com>"]

[lib]
name = "crypt3_nif"
crate-type = ["dylib"]

[dependencies]
bincode = "1.2.1"
crypt3 = "0.1"
rustler = "0.22.0-rc.0"
siphasher = "0.3.3"
serde = { version = "1.0", features = ["derive"] }
